version: '2'
services:
    testappgit-app:
        image: testappgit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testappgit-postgresql:5432/testappgit
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testappgit-postgresql:
        extends:
            file: postgresql.yml
            service: testappgit-postgresql
